# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dev\Meus Projetos\spritemator\ui\newSpriteDialog.ui'
#
# Created: Fri Aug 29 20:35:42 2014
#      by: PyQt5 UI code generator 5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_newSpriteDialog(object):
    def setupUi(self, newSpriteDialog):
        newSpriteDialog.setObjectName("newSpriteDialog")
        newSpriteDialog.resize(286, 215)
        self.verticalLayout = QtWidgets.QVBoxLayout(newSpriteDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupSize = QtWidgets.QGroupBox(newSpriteDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupSize.sizePolicy().hasHeightForWidth())
        self.groupSize.setSizePolicy(sizePolicy)
        self.groupSize.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupSize.setObjectName("groupSize")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupSize)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupMainLayout = QtWidgets.QVBoxLayout()
        self.groupMainLayout.setObjectName("groupMainLayout")
        self.customSizeLayout = QtWidgets.QVBoxLayout()
        self.customSizeLayout.setObjectName("customSizeLayout")
        self.radioCustom = QtWidgets.QRadioButton(self.groupSize)
        self.radioCustom.setChecked(True)
        self.radioCustom.setObjectName("radioCustom")
        self.buttonGroup = QtWidgets.QButtonGroup(newSpriteDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioCustom)
        self.customSizeLayout.addWidget(self.radioCustom)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelWidth = QtWidgets.QLabel(self.groupSize)
        self.labelWidth.setObjectName("labelWidth")
        self.horizontalLayout_3.addWidget(self.labelWidth)
        self.spinWidth = QtWidgets.QSpinBox(self.groupSize)
        self.spinWidth.setMinimum(1)
        self.spinWidth.setMaximum(4096)
        self.spinWidth.setProperty("value", 320)
        self.spinWidth.setObjectName("spinWidth")
        self.horizontalLayout_3.addWidget(self.spinWidth)
        self.customSizeLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelHeight = QtWidgets.QLabel(self.groupSize)
        self.labelHeight.setObjectName("labelHeight")
        self.horizontalLayout_4.addWidget(self.labelHeight)
        self.spinHeight = QtWidgets.QSpinBox(self.groupSize)
        self.spinHeight.setMinimum(1)
        self.spinHeight.setMaximum(4096)
        self.spinHeight.setProperty("value", 240)
        self.spinHeight.setObjectName("spinHeight")
        self.horizontalLayout_4.addWidget(self.spinHeight)
        self.customSizeLayout.addLayout(self.horizontalLayout_4)
        self.groupMainLayout.addLayout(self.customSizeLayout)
        self.presetSizesLayout = QtWidgets.QVBoxLayout()
        self.presetSizesLayout.setObjectName("presetSizesLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio16 = QtWidgets.QRadioButton(self.groupSize)
        self.radio16.setObjectName("radio16")
        self.buttonGroup.addButton(self.radio16)
        self.horizontalLayout.addWidget(self.radio16)
        self.radio32 = QtWidgets.QRadioButton(self.groupSize)
        self.radio32.setObjectName("radio32")
        self.buttonGroup.addButton(self.radio32)
        self.horizontalLayout.addWidget(self.radio32)
        self.radio64 = QtWidgets.QRadioButton(self.groupSize)
        self.radio64.setObjectName("radio64")
        self.buttonGroup.addButton(self.radio64)
        self.horizontalLayout.addWidget(self.radio64)
        self.radio128 = QtWidgets.QRadioButton(self.groupSize)
        self.radio128.setObjectName("radio128")
        self.buttonGroup.addButton(self.radio128)
        self.horizontalLayout.addWidget(self.radio128)
        self.presetSizesLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio24 = QtWidgets.QRadioButton(self.groupSize)
        self.radio24.setObjectName("radio24")
        self.buttonGroup.addButton(self.radio24)
        self.horizontalLayout_2.addWidget(self.radio24)
        self.radio48 = QtWidgets.QRadioButton(self.groupSize)
        self.radio48.setObjectName("radio48")
        self.buttonGroup.addButton(self.radio48)
        self.horizontalLayout_2.addWidget(self.radio48)
        self.radio96 = QtWidgets.QRadioButton(self.groupSize)
        self.radio96.setObjectName("radio96")
        self.buttonGroup.addButton(self.radio96)
        self.horizontalLayout_2.addWidget(self.radio96)
        self.radio256 = QtWidgets.QRadioButton(self.groupSize)
        self.radio256.setObjectName("radio256")
        self.buttonGroup.addButton(self.radio256)
        self.horizontalLayout_2.addWidget(self.radio256)
        self.presetSizesLayout.addLayout(self.horizontalLayout_2)
        self.groupMainLayout.addLayout(self.presetSizesLayout)
        self.verticalLayout_5.addLayout(self.groupMainLayout)
        self.verticalLayout.addWidget(self.groupSize)
        self.layoutButtons = QtWidgets.QHBoxLayout()
        self.layoutButtons.setObjectName("layoutButtons")
        self.buttonCancel = QtWidgets.QPushButton(newSpriteDialog)
        self.buttonCancel.setObjectName("buttonCancel")
        self.layoutButtons.addWidget(self.buttonCancel)
        self.buttonCreate = QtWidgets.QPushButton(newSpriteDialog)
        self.buttonCreate.setObjectName("buttonCreate")
        self.layoutButtons.addWidget(self.buttonCreate)
        self.verticalLayout.addLayout(self.layoutButtons)

        self.retranslateUi(newSpriteDialog)
        QtCore.QMetaObject.connectSlotsByName(newSpriteDialog)

    def retranslateUi(self, newSpriteDialog):
        _translate = QtCore.QCoreApplication.translate
        newSpriteDialog.setWindowTitle(_translate("newSpriteDialog", "New Sprite"))
        self.groupSize.setTitle(_translate("newSpriteDialog", "Size"))
        self.radioCustom.setText(_translate("newSpriteDialog", "Custom"))
        self.labelWidth.setText(_translate("newSpriteDialog", "Width:"))
        self.labelHeight.setText(_translate("newSpriteDialog", "Height:"))
        self.radio16.setText(_translate("newSpriteDialog", "16x16"))
        self.radio32.setText(_translate("newSpriteDialog", "32x32"))
        self.radio64.setText(_translate("newSpriteDialog", "64x64"))
        self.radio128.setText(_translate("newSpriteDialog", "128x128"))
        self.radio24.setText(_translate("newSpriteDialog", "24x24"))
        self.radio48.setText(_translate("newSpriteDialog", "48x48"))
        self.radio96.setText(_translate("newSpriteDialog", "96x96"))
        self.radio256.setText(_translate("newSpriteDialog", "256x256"))
        self.buttonCancel.setText(_translate("newSpriteDialog", "Cancel"))
        self.buttonCreate.setText(_translate("newSpriteDialog", "Create"))

